- class-mixed-content-fixer.php
- rlrsssl-really-simple-ssl.php
redirect kick in on earlier hook.
> Added srcurl to mixed content fixer

- class-admin.php
- class-multisite.php
- readme.txt
increased user capability to activate_plugins
> multisite bug and user cap

- css/main.css
Thanks for pointing this out! Will merge this.
> Missing Semicolon

- class-admin.php
- class-cache.php
- class-front-end.php
- class-help.php
- class-mixed-content-fixer.php
- class-multisite.php
- class-server.php
- force-deactivate.txt
- readme.txt
- rlrsssl-really-simple-ssl.php
- ssl-test-page.php
- testssl/cdn/ssl-test-page.html
- testssl/cloudflare/ssl-test-page.html
- testssl/cloudfront/ssl-test-page.html
- testssl/envhttps/ssl-test-page.html
- testssl/loadbalancer/ssl-test-page.html
- testssl/serverhttps1/ssl-test-page.html
- testssl/serverhttpson/ssl-test-page.html
- testssl/serverport443/ssl-test-page.html
While translating for en_CA found a few items so I've gone through and corrected them. Probably went overboard as I did some dev comments too. Feel free to ignore any of them.
Cheers
> Grammar, Spelling & Capitalizations

- readme.txt
- rlrsssl-really-simple-ssl.php
#	class-admin.php
#	class-front-end.php
> upped version to 25

- readme.txt
Super minor spelling found while translating
> Fixed spelling of explicitly

- class-admin.php
Disable Javascript redirect by default.
> Disable Javascript redirect by default

- class-admin.php
- readme.txt
- rlrsssl-really-simple-ssl.php
Updated version number and fixed complianz url
> Version, complianz url

- class-admin.php
Always show SSL menu for super admins
> Show SSL menu for super admins

- class-admin.php
- css/main.css
Split notices into functions, actions
> Split notices into functions, actions

- class-admin.php
- css/main.css
> Moved actions

- class-admin.php
- readme.txt
> Updated complianz link

- class-mixed-content-fixer.php
- rlrsssl-really-simple-ssl.php
> No mixed content fixer on XML

- class-admin.php
- readme.txt
updated non translateable string
> updated non translateable string

- class-admin.php
- class-certificate.php
- css/main.css
Fixed a bug where strpos needle/haystack where the wrong way around.
> Improved certificate detection

- class-admin.php
- readme.txt
- rlrsssl-really-simple-ssl.php
> Removed capability checks

- class-admin.php
> cool checkboxes

- class-admin.php
Checkbox value is now being returned
> Checkbox value is now being returned

- class-admin.php
- readme.txt
exclude acme-challenge for Let’s Encrypt verification.
> Excluded acme-challenge

- class-admin.php
- class-certificate.php
Added transients for htaccess test, ssl test page and mixed content
fixer detected
> Added transients for htaccess test, ssl test page and mixed content fixer detected

- readme.txt
- rlrsssl-really-simple-ssl.php
> readme and versioning

- class-certificate.php
increased transient time for certificate check, always run on SSL
settings page.
> increased transient time for certificate check

- class-admin.php
Cached mixed content fixer results, added new warning when HTTP status
!= 200, linking to an article explaining how to fix.
> improved mixed content fixer detected

- class-admin.php
Updated no SSL detected notice and Complianz name.
> Updated no SSL detected notice

- class-admin.php
renamed auto replace mixed content to mixed content fixer
> renamed auto replace mixed content
